---
# file: roles/linux_common/tasks/apt_install.yml

# install ppas
- name: apt_install | install ppas
  apt_repository: 'repo="{{ item }}" state=present update_cache=yes'
  sudo: yes
  with_items: apt_repos

# only update apt cache if it's 24 hours old or more
- name: apt_install | update apt cache
  apt: update_cache=yes cache_valid_time=86400
  sudo: yes
  failed_when: False

# install packages
- name: apt_install | install packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_flattened:
    - apt_packages
    - packages

# vim:ft=ansible:
