---
# file: roles/framework/reactjs/tasks/main.yml

- name: npm install reactjs
  npm: >
    name=reactjs
    global=yes
    state=present
    path={{ node_modules_path }}
#   ignore_scripts=[yes|no]: Use the --ignore-scripts flag when installing
#   production=[yes|no]: install deps in production mode, excluding devDeps
#   registry: the registry to install modules from
#   version: the version to be installed
  become: '"{{ ansible_user_id }}" != "root"'

# vim:ft=ansible:
