---
# file: roles/nginx/tasks/apt_install.yml

# to version pin:  name=nginx={{ nginx_version }}
- name: apt_install | install NGINX package
  apt:
      name=nginx
      state=present
      update_cache=yes
  become: '"{{ ansible_user_id }}" != "root"'

- name: apt_install | ensure service is running/active and enabled on boot
  service:
      name=nginx
      enabled=yes
      state=started
  become: '"{{ ansible_user_id }}" != "root"'
  tags:
      - service

# vim:ft=ansible:
