---
# file: roles/nginx/tasks/yum_install.yml

- name: yum_install | check if nginx is installed
  action: command yum list installed nginx
  register: yum_list_nginx
  failed_when: False
  changed_when: False

- name: yum_install | install repository file
  template:
      src=nginx.repo.j2
      dest=/etc/yum.repos.d/nginx-{{ nginx_version }}.repo
      owner=root
      group=root
      mode=0644
  become: yes

- name: yum_install | install NGINX package
  yum:
      pkg=nginx-{{ nginx_version }}
      state=present
      update_cache=yes
  become: yes
  when: 'yum_list_nginx.stdout.find("nginx-{{ nginx_version }}") == -1'

- name: yum_install | ensure service is running/active and enabled on boot
  service:
      name=nginx
      enabled=yes
      state=started
  become: yes
  tags:
      - service

# vim:ft=ansible:
