#!/bin/bash
truncate hosts --size 0
docker_ids=$(docker ps --format '{{.ID}}'| tr '\n' ' ')
for did in $docker_ids; do
  dname=$(docker container ls --filter=id=$did --format='{{.Names}}')
  dinfo=$(docker inspect $did)
  dport=$(echo $dinfo | jq -r ".[].NetworkSettings.Ports.\"22/tcp\"[].HostPort")
  echo "$dname ansible_host=$did ansible_ssh_port=$dport ansible_connection=docker" >> hosts
done
