---
# file: roles/kibana/tasks/install.yml

- name: ensure presence of kibana user
  user: name={{ kibana_user }} state=present

- name: ensure kibana home directory
  file: path={{ kibana_home }} state=directory owner={{ kibana_user }}

- name: download kibana package
  get_url: url={{ kibana_pkg_url }} dest=/tmp/{{ kibana_pkg }} owner={{ kibana_user }}

- name: extract kibana package contents
  unarchive: remote_src=yes
    src=/tmp/{{ kibana_pkg }}
    dest={{ kibana_home }}
    owner={{ kibana_user }}
    keep_newer=yes
    extra_opts="--strip-components=1"

# vim:ft=ansible
