---
# file: roles/kibana/tasks/main.yml
# TODO support darwin/windows

- include: install.yml
  become: '"{{ ansible_user_id }}" != "root"'
  tags:
    - install

- include: config.yml
  become: '"{{ ansible_user_id }}" != "root"'

#- name: start kibana service, enable on boot
#  service:
#    name=kibana{{ kibana_version_major }}
#    state=started
#    enabled=yes       # enabled on boot
#  become: '"{{ ansible_user_id }}" != "root"'
#
#- name: wait for kibana port to open
#  wait_for: port={{ service.port }} state=started timeout=60

# vim:ft=ansible
