---
# vars file for packer

packer_url: 'https://dl.bintray.com/mitchellh/packer'
packer_version: ""
packer_os: '{{ ansible_system.lower() }}'
packer_arch: "{{ ansible_architecture | regex_replace('x86_64','amd64') | regex_replace('i386','386') }}"
packer_download_dir: "/tmp"
packer_install_dir: "/usr/local/bin"

# vim:ft=ansible:
