# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "Centos65"
    centos.vm.box_url = "https://vagrantcloud.com/nrel/boxes/CentOS-6.5-x86_64/versions/1.2.0/providers/virtualbox.box"

    centos.vm.host_name = "centos"
    centos.vm.network :private_network, ip: "10.10.10.20"
    centos.vm.provider :virtualbox do |vb|
      vb.name = "centos_vm"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    centos.vm.network "forwarded_port", guest: 80, host: 8020
  end
end
