---
# file: roles/windows_common/tasks/reboot_host.yml

- name: reboot_host | restart the server if we must
  raw: 'shutdown /r /t 0'

- name: reboot_host | wait for the server to shutdown
  local_action: wait_for
    host={{ ansible_ssh_host }}
    state=stopped
    delay=30
    connect_timeout=5
    timeout=60

- name: reboot_host | wait for the server to come back up
  local_action: wait_for
    host={{ ansible_ssh_host }}
    port={{ ansible_ssh_port }}
    state=started
    delay=10
    connect_timeout=5
    timeout=60

# vim:ft=ansible:
