# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "trusty64"
    ubuntu.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/20150609.0.10/providers/virtualbox.box"

    ubuntu.vm.host_name = "ubuntu"
    ubuntu.vm.network :private_network, ip: "10.10.10.30"
    ubuntu.vm.provider :virtualbox do |vb|
      vb.name = "ubuntu_vm"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    ubuntu.vm.network "forwarded_port", guest: 80, host: 8030

    ##############
    ### ANSIBLE ##
    ##############
    #config.vm.provision "ansible" do |ansible|
    #  ansible.playbook = "/path/to/playbooks/vagrants.yml"
    #end

  end
end
