---
# vars file for terraform

terraform_url: 'https://dl.bintray.com/mitchellh/terraform'
terraform_version: ""
terraform_os: '{{ ansible_system.lower() }}'
terraform_arch: "{{ ansible_architecture | regex_replace('x86_64','amd64') | regex_replace('i386','386') }}"
terraform_download_dir: "/tmp"
terraform_install_dir: "/usr/local/bin"

# vim:ft=ansible:
