---
# file: playbooks/ansiblizer.yml

- hosts: ansibles
  roles:

    - role: linux_common
      packages:
        - sshpass
        - sshfs
        - ansible
        - python-pip
      yum_packages:
        - epel-release
      apt_packages:
        - software-properties-common
      apt_repos:
        - 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main'
      python_packages:
        - httplib2
        - urlparse2

    - role: ansible

# vim:ft=ansible:
